/**
 * Placeholder linked customers + detail payload until Customer Information fetch API exists.
 * Shape mirrors Interface Delight CustomerInformationPanel mock structure.
 */

const defaultChannels = () => [
  { mailType: "SMS", allow: true, bestTime: "10:00", days: { mon: true, tue: true, wed: false, thu: true, fri: true, sat: false, sun: false } },
  { mailType: "Email", allow: true, bestTime: "09:00", days: { mon: true, tue: true, wed: true, thu: true, fri: true, sat: false, sun: false } },
  { mailType: "Letter", allow: false, bestTime: "", days: { mon: false, tue: false, wed: false, thu: false, fri: false, sat: false, sun: false } },
  { mailType: "Voice Broadcast", allow: false, bestTime: "", days: { mon: false, tue: false, wed: false, thu: false, fri: false, sat: false, sun: false } },
];

const commDraft = (mobile, email) => ({
  language: "english",
  contactNo: mobile,
  emailId: email,
  preferredChannel: "sms",
  optInMarketing: false,
  optOutCalls: false,
  channels: defaultChannels(),
});

export const MOCK_LINKED_CUSTOMERS = [
  {
    id: "C001",
    name: "Raj Y Patel",
    role: "Borrower",
    customerNo: "CUST-10045",
    accountNo: "16October2025__001",
    delinquent: "Y",
    portfolio: "Auto Finance",
    odAmount: 35000,
    osAmount: 150000,
    details: {
      dob: "1985-03-15",
      pob: "Mumbai",
      regionalName: "राज पटेल",
      alias: "R. Patel",
      nationality: "Indian",
      gender: "Male",
      marital: "Married",
      stayedYears: 12,
      familyIncome: 1200000,
      children: 2,
      dependents: 4,
      mobile: "+91 98765 43210",
      email: "raj.patel@email.com",
    },
    employment: {
      occupation: "Salaried",
      employer: "TechCorp India Pvt Ltd",
      designation: "Senior Manager",
      annualSalary: 1800000,
    },
    financial: {
      bankAccount: "XXXX-XXXX-4523",
      bank: "HDFC Bank",
      branch: "Andheri West",
    },
    addresses: [
      {
        type: "Residential",
        desc: "Primary Residence",
        zip: "400001",
        city: "Mumbai",
        address1: "42 MG Road",
        address2: "Andheri West",
        state: "Maharashtra",
        country: "India",
        contact: "Raj Patel",
        tel: "+91 22 2634 5678",
        fax: "",
        mobile: "+91 98765 43210",
        pager: "",
        email: "raj.patel@email.com",
      },
      {
        type: "Office",
        desc: "Workplace",
        zip: "400051",
        city: "Mumbai",
        address1: "TechCorp Tower, 5th Floor",
        address2: "BKC",
        state: "Maharashtra",
        country: "India",
        contact: "Reception",
        tel: "+91 22 4567 8901",
        fax: "+91 22 4567 8902",
        mobile: "",
        pager: "",
        email: "raj.patel@techcorp.com",
      },
    ],
    groupAccounts: [
      {
        agreementNo: "16October2025__001",
        currentDelqDays: 45,
        currentAmount: 35000,
        peakDelqDays: 60,
        peakAmount: 52000,
        promiseTaken: 3,
        promiseBroken: 1,
        currentBucket: 2,
        nextBucketDate: "2025-11-01",
        nextBucketDaysLeft: 15,
      },
      {
        agreementNo: "16October2025__002",
        currentDelqDays: 0,
        currentAmount: 0,
        peakDelqDays: 15,
        peakAmount: 12000,
        promiseTaken: 1,
        promiseBroken: 0,
        currentBucket: 0,
        nextBucketDate: "—",
        nextBucketDaysLeft: 0,
      },
    ],
    communicationDraft: commDraft("+91 98765 43210", "raj.patel@email.com"),
  },
  {
    id: "C002",
    name: "Meena Patel",
    role: "Co-Borrower",
    customerNo: "CUST-10046",
    accountNo: "16October2025__001",
    delinquent: "Y",
    portfolio: "Auto Finance",
    odAmount: 35000,
    osAmount: 150000,
    details: {
      dob: "1988-07-22",
      pob: "Pune",
      regionalName: "मीना पटेल",
      alias: "",
      nationality: "Indian",
      gender: "Female",
      marital: "Married",
      stayedYears: 8,
      familyIncome: 1200000,
      children: 2,
      dependents: 4,
      mobile: "+91 87654 32109",
      email: "meena.p@email.com",
    },
    employment: {
      occupation: "Self-Employed",
      employer: "Patel Enterprises",
      designation: "Director",
      annualSalary: 900000,
    },
    financial: {
      bankAccount: "XXXX-XXXX-7891",
      bank: "ICICI Bank",
      branch: "Bandra East",
    },
    addresses: [
      {
        type: "Residential",
        desc: "Primary Residence",
        zip: "400001",
        city: "Mumbai",
        address1: "42 MG Road",
        address2: "Andheri West",
        state: "Maharashtra",
        country: "India",
        contact: "Meena Patel",
        tel: "",
        fax: "",
        mobile: "+91 87654 32109",
        pager: "",
        email: "meena.p@email.com",
      },
    ],
    groupAccounts: [
      {
        agreementNo: "16October2025__001",
        currentDelqDays: 45,
        currentAmount: 35000,
        peakDelqDays: 60,
        peakAmount: 52000,
        promiseTaken: 3,
        promiseBroken: 1,
        currentBucket: 2,
        nextBucketDate: "2025-11-01",
        nextBucketDaysLeft: 15,
      },
    ],
    communicationDraft: commDraft("+91 87654 32109", "meena.p@email.com"),
  },
  {
    id: "C003",
    name: "Suresh Kumar",
    role: "Guarantor",
    customerNo: "CUST-10099",
    accountNo: "16October2025__001",
    delinquent: "N",
    portfolio: "Auto Finance",
    odAmount: 0,
    osAmount: 0,
    details: {
      dob: "1975-11-02",
      pob: "Delhi",
      regionalName: "",
      alias: "S. Kumar",
      nationality: "Indian",
      gender: "Male",
      marital: "Married",
      stayedYears: 20,
      familyIncome: 2500000,
      children: 3,
      dependents: 5,
      mobile: "+91 99887 76655",
      email: "suresh.k@email.com",
    },
    employment: {
      occupation: "Business Owner",
      employer: "Kumar Trading Co",
      designation: "Proprietor",
      annualSalary: 3600000,
    },
    financial: {
      bankAccount: "XXXX-XXXX-1234",
      bank: "SBI",
      branch: "Connaught Place",
    },
    addresses: [
      {
        type: "Residential",
        desc: "Home",
        zip: "110001",
        city: "New Delhi",
        address1: "15 Janpath Road",
        address2: "",
        state: "Delhi",
        country: "India",
        contact: "Suresh Kumar",
        tel: "+91 11 2345 6789",
        fax: "",
        mobile: "+91 99887 76655",
        pager: "",
        email: "suresh.k@email.com",
      },
    ],
    groupAccounts: [],
    communicationDraft: commDraft("+91 99887 76655", "suresh.k@email.com"),
  },
];
