import { getIntegrationFrameworkApiPath } from "@shared/config/apiConstants";

export const IntegrationFrameworkAPI = {
  getMetaData: () => `${getIntegrationFrameworkApiPath()}getmetadata`,
  getStatusHeaderMatch: () => `${getIntegrationFrameworkApiPath()}getstatusheadermatch`,
  testDbConnection: () => `${getIntegrationFrameworkApiPath()}testdbconnection`,
  getGeneratedFileNames: () => `${getIntegrationFrameworkApiPath()}getgeneratedfilenames`,
  addListener: () => `${getIntegrationFrameworkApiPath()}addListener`,
  newUpload: () => `${getIntegrationFrameworkApiPath()}newupload`,
  getAllFilesHeaders: () => `${getIntegrationFrameworkApiPath()}getallfilesheaders`,
  publishCSV: () => `${getIntegrationFrameworkApiPath()}publishCsv`,
  convertXmlToJson: () => `${getIntegrationFrameworkApiPath()}convertXmlToJson`,
  convertJsonToXml: () => `${getIntegrationFrameworkApiPath()}convertJsonToXml`,
  retryData: (modifiedTopicName) => `${getIntegrationFrameworkApiPath()}getdata?topicName=${modifiedTopicName}`,
  sendRetryData: () => `${getIntegrationFrameworkApiPath()}senddataretrydata`,
  deleteData: () => `${getIntegrationFrameworkApiPath()}deleteData`,
  existingFileUpload: () => `${getIntegrationFrameworkApiPath()}existingupload`,
  sendApiCall: () => `${getIntegrationFrameworkApiPath()}send-api-call`,
  getApiFilenames: () => `${getIntegrationFrameworkApiPath()}get-api-filenames`,
  existingApiProcess: () => `${getIntegrationFrameworkApiPath()}existing-api-process`,
  path: () => `${getIntegrationFrameworkApiPath()}path`,
  apiConfig: () => `${getIntegrationFrameworkApiPath()}api-config`,
  externalApi: () => `${getIntegrationFrameworkApiPath()}external-api`,
  getMetaDataContent: (fileName) => `${getIntegrationFrameworkApiPath()}metadata/${fileName}`,
  fetchTables: () => `${getIntegrationFrameworkApiPath()}tables`,
  tableMetadata: () => `${getIntegrationFrameworkApiPath()}table-metadata`,
  getTargetTables: () => `${getIntegrationFrameworkApiPath()}target-tables`,
  fetchTargetColumns: () => `${getIntegrationFrameworkApiPath()}target-columns`,
  saveMetadata: () => `${getIntegrationFrameworkApiPath()}save-metadata`,
  fileConversion: () => `${getIntegrationFrameworkApiPath()}file-conversion`,
  getDbFilenames: () => `${getIntegrationFrameworkApiPath()}get-db-filenames`,
  generateQueries: (fileName,Topic) => `${getIntegrationFrameworkApiPath()}generateQueries?fileName=${fileName}&topicName=${Topic}`,
  jsonMetadata: () => `${getIntegrationFrameworkApiPath()}json-metadata`,
  xmlMetadata: () => `${getIntegrationFrameworkApiPath()}xml-metadata`,
};