server {
    listen       80;
    server_name  _;
    root         /usr/share/nginx/html;

    # SPA is built with Vite base: '/drs/'
    location /drs/ {
        try_files $uri $uri/ /drs/index.html;

        add_header Content-Security-Policy "default-src 'self';connect-src 'self' ${CSP_CONNECT_ORIGIN};script-src 'self' ${CSP_CONNECT_ORIGIN};script-src-elem 'self' ${CSP_CONNECT_ORIGIN};img-src 'self' data:;style-src 'self' 'nonce-${CSP_STYLE_NONCE}' https://fonts.googleapis.com;style-src-elem 'self' 'nonce-${CSP_STYLE_NONCE}' https://fonts.googleapis.com;font-src 'self' data: https://fonts.gstatic.com;object-src 'none';base-uri 'self';form-action 'self';frame-src 'self' blob: ${CSP_CONNECT_ORIGIN};media-src 'none';worker-src 'self';manifest-src 'self';block-all-mixed-content;" always;
    }

    # Avoid browsers caching API endpoints after container env changes
    location = /drs/config.json {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
    }

    location = / {
        return 302 /drs/;
    }
}
